name: CI/CD Pipeline

# Trigger the workflow on specific events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"  # Runs every day at 2:00 AM UTC

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirment.txt 
        pip install pytest flake8

    # Step 4: Run flake8 for code quality checks
    - name: Code quality check (flake8)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Step 5: Run pytest for testing
    - name: Run tests with pytest
      run: |
        pytest

  notify:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Notify on Failure
      if: failure()
      run: echo "One or more jobs failed. Please review the pipeline logs."
