name: CI/CD Pipeline

# Events that trigger the workflow
on:
  # Trigger when code is pushed to the main branch
  push:
    branches:
      - main
  # Trigger when a pull request is opened or updated for the main branch
  pull_request:
    branches:
      - main
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"

# Define jobs for the workflow
jobs:
  test_and_lint:
    # Use the latest Ubuntu environment
    runs-on: ubuntu-latest

    # Steps to execute in this job
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Specify the Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8

      # Step 4: Run flake8 for code quality checks
      - name: Run flake8
        run: |
          # Ensure the entire codebase adheres to PEP 8 standards
          flake8 .
          max-line-length = 88
          ignore = E501  
        # Optionally, include flags like `--max-line-length=88` for customization

      # Step 5: Run pytest for tests
      - name: Run pytest
        run: |
          # Execute all test cases in the project
          pytest
